const ROUND = "round";
const IS_END = "is_End";
const CURR_BIRD = "currentBird"
const STYLE_CORRECT = 'STYLE_CORRECT'
const STYLE_INCORRECT = 'STYLE_INCORRECT'
const STYLE_RESET = 'STYLE_RESET'
const SCORE_UP = 'SCORE_UP'
const SCORE_DOWN = "SCORE_DOWN"

export { ROUND, IS_END, CURR_BIRD, STYLE_CORRECT, STYLE_INCORRECT, STYLE_RESET, SCORE_DOWN, SCORE_UP };